services:
  bot:
    build: .
    container_name: tg-bot
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
      - ./data:/app/data # for SQLite DB file persistence
    environment:
      DB_PATH: /app/data/database.sqlite
    ports:
      - "8080:8080"
# no db service needed
